### ISSUE TITLE
Check for schedule change

### ISSUE THREAD

**Issue by glen442** [tim1mw/pycon_capture#23]
At the moment the metadata is loaded once when the web page is opened. 

Alternatives include:
Ajax to refresh the schedule between sessions

**Comment by tim1mw** [comment]
This caused a problem on Tuesday when a late schedule changed caused the Ferrier room to be "closed down" too early.

**Comment by tim1mw** [comment]
I think this got added at some point and this issue wasn't closed. The code is now refreshing from the live conference feed, so just re-load the video monitor to get the latest schedule. However, that only works if the laptop is online.
